import discord

ichika = discord.Embed(title='호시노 이치카(星乃一歌)', description='성별 : 여', color=0x33AAEE)
ichika.add_field(name='성우', value='노구치 루리코(野口瑠璃子)', inline=False)
ichika.add_field(name='유닛', value='Leo/need', inline=False)
ichika.add_field(name='생일', value='8월 11일', inline=False)
ichika.add_field(name='키', value='161cm', inline=False)
ichika.add_field(name='학교', value='미야마스사카 여학원', inline=False)
ichika.add_field(name='반', value='1학년 C반', inline=False)
ichika.add_field(name='취미', value='미쿠의 노래 감상, 키우고 있는 선인장 바라보기', inline=False)
ichika.add_field(name='특기', value='사과 깎기', inline=False)
ichika.add_field(name='좋아하는 음식', value='야키소바 빵', inline=False)
ichika.add_field(name='싫어하는 음식', value='완두콩', inline=False)
ichika.add_field(name='약점', value='절규계 놀이기구', inline=False)
ichika.add_field(name='자기소개', value='쿨해 보이지만 사실은 친구를 생각하는 상냥한 소녀. 사키, 호나미, 시호와는 소꿉친구이지만, 어떤 사정으로 호나미와 시호와는 관계가 삐걱거리고 있다. 미쿠의 노래를 감상하는 것을 좋아한다. Leo/need에서는 기타와 보컬을 담당한다.', inline=False)
ichika.set_thumbnail(url="https://cdn.discordapp.com/attachments/858612609116012549/874186025327550494/63dd61b0407df850d61fe5f50337b2adc8b819c3bd2ee916db5549220bf1061ea89187b7afaf11683b444a7420275a986ac0.png")
ichika.set_footer(text='Project SEKAI COLOURFUL STAGE! feat.HATSUNE MIKU')

saki = discord.Embed(title='텐마 사키(天馬咲希)', description='성별 : 여', color=0xFFDD44)
saki.add_field(name='성우', value='이소베 카린(礒部花凜)', inline=False)
saki.add_field(name='유닛', value='Leo/need', inline=False)
saki.add_field(name='생일', value='5월 9일', inline=False)
saki.add_field(name='키', value='159cm', inline=False)
saki.add_field(name='학교', value='미야마스사카 여학원', inline=False)
saki.add_field(name='반', value='1학년 C반', inline=False)
saki.add_field(name='취미', value='패션・메이크업 영상 시청, 비즈 악세사리 만들기', inline=False)
saki.add_field(name='특기', value='헤어 어레인지, 공기 놀이', inline=False)
saki.add_field(name='좋아하는 음식', value='스낵 과자', inline=False)
saki.add_field(name='싫어하는 음식', value='죽', inline=False)
saki.add_field(name='약점', value='외톨이', inline=False)
saki.add_field(name='자기소개', value='언제나 밝고 미소가 끊이지 않는 무드 메이커. 선천적으로 병약한 탓에 중학교는 거의 다니지 못했지만, 간신히 건강해져서 고등학교부터 복학한다. 오랜만에 재회할 소꿉친구들과 즐거운 고교 생활을 기대하고 있었지만... Leo/need에서는 키보드 담당.', inline=False)
saki.set_thumbnail(url="https://cdn.discordapp.com/attachments/858612609116012549/874186042377383946/f3ffe3bb44ea2215be47ec9fb4e75857a00fe67527eee01cfd29d86b3496030d861392aa569b704339133fada18a52ce06db.png")
saki.set_footer(text='Project SEKAI COLOURFUL STAGE! feat.HATSUNE MIKU')

honami = discord.Embed(title='모치즈키 호나미(望月穂波)', description='성별 : 여', color=0xEE6666)
honami.add_field(name='성우', value='우에다 레이나(上田麗奈)', inline=False)
honami.add_field(name='유닛', value='Leo/need', inline=False)
honami.add_field(name='생일', value='10월 27일', inline=False)
honami.add_field(name='키', value='166cm', inline=False)
honami.add_field(name='학교', value='미야마스사카 여학원', inline=False)
honami.add_field(name='반', value='1학년 B반', inline=False)
honami.add_field(name='취미', value='강아지와 산책, 가내 텃밭 꾸리기', inline=False)
honami.add_field(name='특기', value='가사 전반, 수영', inline=False)
honami.add_field(name='좋아하는 음식', value='애플파이', inline=False)
honami.add_field(name='싫어하는 음식', value='치즈', inline=False)
honami.add_field(name='약점', value='그림을 그리는 것', inline=False)
honami.add_field(name='자기소개', value='문무겸비의 우등생으로, 감싸는 듯한 상냥함을 가졌다. 이치카, 사키, 시호와는 소꿉친구였지만, 중학교 시기에 어떤 일을 계기로 이치카 일행과는 거리를 두는 듯이 되버렸다. Leo/need에서는 드럼 담당.', inline=False)
honami.set_thumbnail(url="https://cdn.discordapp.com/attachments/858612609116012549/874186054079500338/44ad314fe7257823c1a99f66d581cf7e6430bc37bf3beafa50a24bb9d6db30db4f472f8c6ff5983b3267a0dba052a6b501a5.png")
honami.set_footer(text='Project SEKAI COLOURFUL STAGE! feat.HATSUNE MIKU')

shiho = discord.Embed(title='히노모리 시호(日野森志歩)', description='성별 : 여', color=0xBBDD22)
shiho.add_field(name='성우', value='나카시마 유키(中島由貴)', inline=False)
shiho.add_field(name='유닛', value='Leo/need', inline=False)
shiho.add_field(name='생일', value='1월 8일', inline=False)
shiho.add_field(name='키', value='159cm', inline=False)
shiho.add_field(name='학교', value='미야마스사카 여학원', inline=False)
shiho.add_field(name='반', value='1학년 A반', inline=False)
shiho.add_field(name='취미', value='좋아하는 걸즈 밴드의 라이브 보러 가기, 베이스의 연습・연주', inline=False)
shiho.add_field(name='특기', value='서예예', inline=False)
shiho.add_field(name='좋아하는 음식', value='라멘, 햄버그', inline=False)
shiho.add_field(name='싫어하는 음식', value='두부', inline=False)
shiho.add_field(name='약점', value='언니', inline=False)
shiho.add_field(name='자기소개', value='어울리기를 싫어하는 고독한 늑대. 자신이 좋아하는 것에 몰두해 주위 사람들이 어떻게 생각하는지 신경쓰지 않는다. 그런 그녀도 과거에는 소꿉친구들과 행동을 같이하며 친구들을 소중하게 생각했었지만... Leo/need에서는 베이스 담당.', inline=False)
shiho.set_thumbnail(url="https://cdn.discordapp.com/attachments/858612609116012549/874186066654019645/aa83b0e1842ada0825dc645cbe4d2955e810f0a061384a7044800cff707c804d9652c115920b350f4031595630aa2ad26823.png")
shiho.set_footer(text='Project SEKAI COLOURFUL STAGE! feat.HATSUNE MIKU')